using Microsoft.AspNetCore.Mvc;
using IT_ELECTIVE_2_PREFINAL_EXAM.Models;

namespace IT_ELECTIVE_2_PREFINAL_EXAM.Controllers
{
    public class ExamController : Controller
    {
        public IActionResult Index()
        {
            var examQuestions = new List<QuestionItem>
            {
                new QuestionItem { Id = 1, Question = "What is the main problem solved by using a database instead of an in-memory collection?", Options = new List<string>{ "A. It makes C# code shorter", "B. It prevents the application from restarting", "C. It allows data to persist after the application stops", "D. It removes the need for MVC" }, CorrectAnswer = "C. It allows data to persist after the application stops", Explanation = "Databases provide persistent storage, retaining data even after the application process terminates." },
                new QuestionItem { Id = 2, Question = "Which approach is being used when an existing database is used to generate EF Core entity classes?", Options = new List<string>{ "A. Code-First", "B. Database-First", "C. Model-First", "D. Controller-First" }, CorrectAnswer = "B. Database-First", Explanation = "Database-First scaffolding generates code entities directly from an existing database schema." },
                new QuestionItem { Id = 3, Question = "What is the primary purpose of Entity Framework Core?", Options = new List<string>{ "A. To create HTML pages automatically", "B. To replace the MVC Controller", "C. To map objects in code to relational database data", "D. To replace the C# compiler" }, CorrectAnswer = "C. To map objects in code to relational database data", Explanation = "EF Core acts as an Object-Relational Mapper (ORM) bridging .NET objects with relational databases." },
                new QuestionItem { Id = 4, Question = "Which EF Core component is primarily responsible for communicating with the database?", Options = new List<string>{ "A. DbContext", "B. DbSetView", "C. ControllerContext", "D. RazorContext" }, CorrectAnswer = "A. DbContext", Explanation = "DbContext manages database connections, transactions, and querying." },
                new QuestionItem { Id = 5, Question = "What does the command 'dotnet ef dbcontext scaffold' primarily do?", Options = new List<string>{ "A. Deletes the database", "B. Creates a new MVC project", "C. Generates EF Core models and a DbContext from an existing database", "D. Starts the MVC application" }, CorrectAnswer = "C. Generates EF Core models and a DbContext from an existing database", Explanation = "Scaffolding creates reverse-engineered entity classes and DbContext configuration from an existing database." },
                new QuestionItem { Id = 6, Question = "Where is a database connection string commonly stored in an ASP.NET Core MVC application?", Options = new List<string>{ "A. Program.cs only", "B. appsettings.json", "C. Index.cshtml", "D. Student.cs" }, CorrectAnswer = "B. appsettings.json", Explanation = "appsettings.json stores application configuration settings like database connection strings." },
                new QuestionItem { Id = 7, Question = "A Student belongs to exactly one Section, while a Section can contain many students. What type of relationship is this?", Options = new List<string>{ "A. One-to-One", "B. One-to-Many", "C. Many-to-Many", "D. Many-to-One only" }, CorrectAnswer = "B. One-to-Many", Explanation = "A single section parent record links to multiple student child records." },                new QuestionItem { Id = 8, Question = "In the provided example, what is SectionId?", Options = new List<string>{ "A. Primary key of Student", "B. Foreign key referencing Section", "C. Navigation property", "D. Database connection string" }, CorrectAnswer = "B. Foreign key referencing Section", Explanation = "SectionId holds the foreign key value linking Student to the Section entity." },
                new QuestionItem { Id = 8, Question = "In the provided example, what is SectionId?", Options = new List<string>{ "A. Primary key of Student", "B. Foreign key referencing Section", "C. Navigation property", "D. Database connection string" }, CorrectAnswer = "B. Foreign key referencing Section", Explanation = "SectionId holds the foreign key value linking Student to the Section entity." },
                new QuestionItem { Id = 9, Question = "What is the purpose of a navigation property such as public Section Section { get; set; }?", Options = new List<string>{ "A. It stores the database password", "B. It represents a relationship to another entity", "C. It creates a new database", "D. It validates the student's name" }, CorrectAnswer = "B. It represents a relationship to another entity", Explanation = "Navigation properties enable object reference access between related domain models." },
                new QuestionItem { Id = 10, Question = "What does .Include() generally allow EF Core to do?", Options = new List<string>{ "A. Delete the Section table", "B. Load related Section data together with Students", "C. Create a new Student", "D. Validate Student input" }, CorrectAnswer = "B. Load related Section data together with Students", Explanation = ".Include() triggers eager loading for related navigation property data." },
                new QuestionItem { Id = 11, Question = "Why might a ViewModel be used when displaying Student and Section information?", Options = new List<string>{ "A. To replace the database", "B. To combine or shape the data specifically needed by the view", "C. To automatically create database tables", "D. To prevent controllers from using LINQ" }, CorrectAnswer = "B. To combine or shape the data specifically needed by the view", Explanation = "ViewModels encapsulate tailored view data without exposing raw domain entities directly." },
                new QuestionItem { Id = 12, Question = "What is the main benefit of Include(s => s.Section)?", Options = new List<string>{ "A. It loads the related Section navigation property", "B. It creates a Section object manually", "C. It removes the foreign key", "D. It prevents the query from accessing the database" }, CorrectAnswer = "A. It loads the related Section navigation property", Explanation = "It ensures that the Section navigation property is eagerly fetched alongside Student data." },
                new QuestionItem { Id = 13, Question = "Which type of validation occurs in the browser before a request is sent to the server?", Options = new List<string>{ "A. Database-level validation", "B. Client-side validation", "C. Server-side validation", "D. EF Core migration validation" }, CorrectAnswer = "B. Client-side validation", Explanation = "Client-side validation runs in JavaScript/HTML before HTTP requests reach the server." },
                new QuestionItem { Id = 14, Question = "Why is server-side validation still necessary if client-side validation exists?", Options = new List<string>{ "A. Client-side validation can be bypassed", "B. Client-side validation automatically modifies the database", "C. Server-side validation only works with SQLite", "D. Client-side validation cannot display messages" }, CorrectAnswer = "A. Client-side validation can be bypassed", Explanation = "Clients can bypass browser scripts; server checks are essential for data integrity and security." },
                new QuestionItem { Id = 15, Question = "Which rule best represents the requirement that every student have a unique Student Number?", Options = new List<string>{ "A. Student Number should always be nullable", "B. Student Number should be unique", "C. Student Number should always be the same", "D. Student Number should contain only spaces" }, CorrectAnswer = "B. Student Number should be unique", Explanation = "Uniqueness guarantees distinct entity identification across the dataset." },
                new QuestionItem { Id = 16, Question = "Which is the best reason for having a database-level unique constraint on StudentNumber?", Options = new List<string>{ "A. It protects data integrity even if application-level validation is bypassed", "B. It makes Razor Views render faster", "C. It removes the need for a Controller", "D. It automatically creates a ViewModel" }, CorrectAnswer = "A. It protects data integrity even if application-level validation is bypassed", Explanation = "Database constraints enforce strict rules directly at the data storage engine level." },
                new QuestionItem { Id = 17, Question = "What is the purpose of a try...catch block in a controller?", Options = new List<string>{ "A. To create navigation properties", "B. To catch and handle exceptions that may occur during execution", "C. To generate database tables", "D. To perform client-side validation" }, CorrectAnswer = "B. To catch and handle exceptions that may occur during execution", Explanation = "Try-catch blocks handle runtime exceptions cleanly without crashing the application process." },


            };

            return View(examQuestions);
        }
    }
}